[workspace]

members = [
  "puzzle1",
  "puzzle2",
  "puzzle3",
  "puzzle4",
  "puzzle5",
  "puzzle6",
  # "puzzle7" will be added when I know how to make linked lists
  "puzzle8",
  "puzzle9",
  "puzzle10",
  "puzzle11",
]
